/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5c2bc6b6-d2c7-454d-8f01-2543d99fe1d0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vWXHXHCXA",
    "aws_user_pools_web_client_id": "50mi674f2krjlnb3lit090j230",
    "oauth": {
        "domain": "realitystockwatch5a009e69-5a009e69-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://wepdqc6pfbbqbg7zmlggxnp4mm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
