import '../styles/globals.scss';
import RealityStockWatchProvider from '../copied/RealityStockWatchProvider';
import { Navbar } from '../components/Navbar';
import { ArrowLineLeft, ArrowLineRight } from 'phosphor-react';
import Head from 'next/head';
import Logo from '../components/SWLogo';
import clsx from 'clsx';
import styles from '../styles/app.module.scss';
import dynamic from 'next/dynamic';

// const PanelToggle = dynamic(() => import('../components/PanelToggle'), {
//     ssr: false,
// });

function MyApp({ Component, pageProps }) {
    const PanelToggle = dynamic(() => import('../components/PanelToggle'), {
        ssr: false,
    });
    return (
        <>
            <div className={styles.appWrapper}>
                <RealityStockWatchProvider>
                    <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <aside>
                        {/* <button className={styles.mobileNavBtn}>
                            <span>Open menu</span>
                        </button> */}
                        <PanelToggle mobileToggle />
                        <a href="/" className={clsx(styles.navLogo, styles.full)}>
                            <Logo />
                        </a>
                    </aside>
                    <Navbar className={styles.navGrid} />

                    <main className={styles.main}>
                        <h1>Main body area</h1>
                        <p>some fake content</p>
                        <Component {...pageProps} />
                    </main>
                </RealityStockWatchProvider>
            </div>
        </>
    );
}

export default MyApp;
