import '../styles/globals.scss';
import { Navbar } from '../components/Navbar';
import { ArrowLineLeft, ArrowLineRight } from 'phosphor-react';
import Head from 'next/head';
import Logo from '../components/SWLogo';
import clsx from 'clsx';
import styles from '../styles/app.module.scss';
import dynamic from 'next/dynamic';
import 'semantic-ui-css/semantic.min.css';

// const PanelToggle = dynamic(() => import('../components/PanelToggle'), {
//     ssr: false,
// });

function MyApp({ Component, pageProps }) {
    const PanelToggle = dynamic(() => import('../components/PanelToggle'), {
        ssr: false,
    });
    return (
        <>
            <div className={styles.appWrapper}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <aside>
                    {/* <button className={styles.mobileNavBtn}>
                        <span>Open menu</span>
                    </button> */}
                    <PanelToggle mobileToggle />
                    <a href="/" className={clsx(styles.navLogo, styles.full)}>
                        <Logo />
                    </a>
                </aside>
                <Navbar className={styles.navGrid} />

                <main className={styles.main}>
                    <Component {...pageProps} />
                </main>
            </div>
        </>
    );
}

export default MyApp;
