import '../styles/globals.scss';
import { Navbar } from '../components/Navbar';
import { ArrowLineLeft, ArrowLineRight } from 'phosphor-react';
import { SSRProvider } from '@react-aria/ssr';
import Head from 'next/head';
import Logo from '../components/SWLogo';
import LogoNav from '../components/SWLogoNav';
import clsx from 'clsx';
import styles from '../styles/app.module.scss';
import dynamic from 'next/dynamic';
import { Provider } from 'backend/context';
import { useUser } from '/backend/User';
import { NavbarLanding } from 'components/NavbarLanding';

// const PanelToggle = dynamic(() => import('../components/PanelToggle'), {
//     ssr: false,
// });

function MyApp({ Component, pageProps }) {
    const PanelToggle = dynamic(() => import('../components/PanelToggle'), {
        ssr: false,
    });
    const { user } = useUser();
    const nav = !user || !user.loggedIn ? <NavbarLanding /> : <Navbar className={styles.navGrid} />;

    return (
        <Provider>
            <SSRProvider>
                <div className={styles.appWrapper}>
                    <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <aside>
                        {/* <button className={styles.mobileNavBtn}>
                        <span>Open menu</span>
                    </button> */}
                        <PanelToggle mobileToggle />
                        <a href="/" className={clsx(styles.navLogo, styles.full)}>
                            <LogoNav />
                        </a>
                    </aside>
                    {/* <Navbar className={styles.navGrid} />
                    <NavbarLanding /> */}
                    {nav}
                    <main className={styles.main}>
                        <Component {...pageProps} />
                    </main>
                </div>
            </SSRProvider>
        </Provider>
    );
}

export default MyApp;
