import Head from 'next/head';
import { Navbar } from '../components/Navbar';
// import Image from 'next/image';
import Logo from '../components/SWLogo';
import clsx from 'clsx';
import styles from '../styles/app.module.scss';

export default function Home() {
    return (
        <div className={styles.appWrapper}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <aside>
                <a href="/" className={clsx(styles.navLogo, styles.full)}>
                    <Logo />
                    {/* <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span> */}
                </a>
            </aside>
            <Navbar className={styles.navGrid} />

            <main className={styles.main}>
                <h1>Main body area</h1>
                <p>some fake content</p>
            </main>
        </div>
    );
}
